// <auto-generated />
namespace App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class columnnamehospedaje : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnnamehospedaje));
        
        string IMigrationMetadata.Id
        {
            get { return "201710180850289_column-name-hospedaje"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
